entity: shreyaspadhy
project: dds
program: funnel_iclr_sweep.py

method: grid
parameters:
  model.tfinal:
    values: [0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
  model.reference_process_key:
    values: ["oudstl", "pisstl"]
  model.sigma:
    values: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2]
  model.alpha:
    values: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2]

command:
  - python
  - ${program}
  - --config
  - configs/config.py